---
title: "Creating figures for paper"
author: "Jamie Afflerbach"
date: "1/30/2020"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)
library(sf)
library(ggrepel)
library(paletteer)
library(gghighlight)


# set the mazu data_edit share based on operating system
dir_M             <- c('Windows' = '//mazu.nceas.ucsb.edu/ohi',
                       'Darwin'  = '/Volumes/ohi',    ### connect (cmd-K) to smb://mazu/ohi
                       'Linux'   = '/home/shares/ohi')[[ Sys.info()[['sysname']] ]]
dir_prep <- '~/github/ne-prep'
# shapefiles
# state land boundaries
ne_states  <- sf::st_read(dsn = paste0(path.expand(dir_prep),'/spatial/shapefiles'), layer = 'states', quiet = T)
rgns       <- sf::st_read(dsn = paste0(path.expand(dir_prep),'/spatial/shapefiles'), layer = 'ne_ohi_rgns', quiet = T) #need to use path.expand because readOGR does not read '~'
rgns_simp  <- sf::st_read(dsn = paste0(path.expand(dir_prep),'/spatial/shapefiles'),layer = 'ne_ohi_rgns_simp', quiet = T) #need to use path.expand because readOGR does not read '~'

ne_rgn <- sf::read_sf(dsn = paste0(path.expand(dir_prep),'/spatial/shapefiles'), layer = 'northeast_rgn', quiet = T) #whole region
rgn_data   <- data.frame(rgns) %>% 
  select(-geometry) %>% 
  mutate(area_km2 = as.numeric(levels(area_km2))[area_km2],
         rgn_name = as.character(rgn_name),
         state = ifelse(str_detect(rgn_name, "Massachusetts"), "Massachusetts", rgn_name))

```


# Figure 1

Region map

```{r Figure 1 region map}

east_coast <- st_union(ne_states) %>%
  st_crop(rgns)

#a lot of this crazy code I copied from this issue on ggrepel: https://github.com/slowkow/ggrepel/issues/89
rgns_sf <- rgns %>%
  mutate(
    CENTROID = purrr::map(geometry, st_centroid),
    COORDS = purrr::map(CENTROID, st_coordinates),
    COORDS_X = purrr::map_dbl(COORDS, 1),
    COORDS_Y = purrr::map_dbl(COORDS, 2)
  ) %>%
  as_tibble() %>%
  st_as_sf()

rgns_sf$nudge_x <- 0
rgns_sf$nudge_y <- 0

x_range <- abs(Reduce("-", range(rgns_sf$COORDS_X)))
y_range <- abs(Reduce("-", range(rgns_sf$COORDS_Y)))

ix <- rgns_sf$rgn_name %in% c("Maine", "New Hampshire", "Rhode Island", "Connecticut", "Massachusetts-North", "Massachusetts-South")
rgns_sf$nudge_x[ix] <- -1 * 0.15 * x_range
rgns_sf$nudge_y[ix] <- 1 * 0.1 * y_range

ix <- rgns_sf$rgn_name %in% c(
  "New York"
)
rgns_sf$nudge_x[ix] <- -1 * 0.2 * x_range
rgns_sf$nudge_y[ix] <- -1 * 0.3 * y_range


ggplot() +
  geom_sf(data = east_coast, fill = "gray80", color = "gray80") +
  geom_sf(data = rgns, fill = "aliceblue", color = "lightblue3") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "aliceblue"),
        axis.text = element_blank(),
        axis.ticks = element_blank())  +
  geom_text_repel(data = rgns_sf,
    mapping = aes(
      x = COORDS_X,
      y = COORDS_Y,
      label = rgn_name
    ),
    nudge_x = rgns_sf$nudge_x,
    nudge_y = rgns_sf$nudge_y,
    size = 2.5,
    min.segment.length = 0,
    point.padding = NA,
    segment.color = "grey50"
  ) +
  coord_sf(crs = st_crs(rgns_sf), datum = NA) +
    theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "aliceblue"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank()) 

ggsave(filename = "figures/region_map.png")

```


# Panel plot

```{r fig.height = 7}
scores <- read_csv("~/github/ne-scores/region/scores.csv") %>%
  filter(dimension == "score") %>%
  left_join(rgn_data, by = c("region_id" = "rgn_id")) %>%
  mutate(goal_name = case_when(
    goal == "BD" ~ "Biodiversity",
    goal == "CW" ~ "Clean Waters",
    goal == "ECO" ~ "LE: Economies",
    goal == "FIS" ~ "FP: Wild-Caught Fisheries",
    goal == "HAB" ~ "BD: Habitats",
    goal == "HS" ~ "Habitat Services",
    goal == "ICO" ~ "SOP: Iconic Species",
    goal == "Index" ~ "Ocean Health Index",
    goal == "LE" ~ "Livelihoods & Economies",
    goal == "LIV" ~ "LE: Livelihoods",
    goal == "LSP" ~ "SOP: Lasting Special Places",
    goal == "MAR" ~ "FP: Aquaculture",
    goal == "RAO" ~ "Resource Acccess Opportunities",
    goal == "SP" ~ "Sense Of Place",
    goal == "SPFIS" ~ "SOP: Fishing Engagement",
    goal == "TR" ~ "Tourism & Recreation",
    goal == "SPP" ~ "BD: Species",
    goal == "FP" ~ "Food Provision"
  ),
  rgn_name = ifelse(region_id == 0, "Northeast", rgn_name),
  year = as.numeric(year),
  weight = ifelse(region_id == 0, 1, 0),
  rgn_dropped = ifelse(region_id == 0, "Northeast", "All other regions"))

ggplot(scores, aes(x = year, y = score, color = rgn_name)) +
  geom_line() +
  facet_wrap(~goal_name, nrow = 3, labeller = labeller(goal_name = label_wrap_gen(width = 25))) +
  theme_minimal() +
  labs(x = "",
       y = "Score") +
  scale_color_paletteer_d("rcartocolor::Safe") + #colorblind 12 color palette
  scale_x_continuous(breaks = c(2005, 2011,  2017), labels = c("2005",  "2011",  "2017")) +
  theme(legend.position = "bottom",
        legend.background = element_rect(fill = "white", colour = NA),
        legend.title = element_blank(),
        legend.text = element_text(size = 11),
        axis.text.x = element_text(size = 9),
        strip.text = element_text(size = 10))

ggsave(filename = "figures/goal_scores_panel_plot.png")
```

```{r, fig.height = 7}

ggplot(scores, aes(x = year, y = score, group = rgn_name, color = rgn_dropped)) +
  geom_line() +
  facet_wrap(~goal_name, nrow = 3, labeller = labeller(goal_name = label_wrap_gen(width = 25))) +
  theme_minimal() +
  labs(x = "",
       y = "Score") +
  scale_color_manual(values = c("grey80", "black")) + #colorblind 12 color palette
  scale_x_continuous(breaks = c(2005, 2011,  2017), labels = c("2005",  "2011",  "2017")) +
    theme(legend.position = "bottom",
        legend.background = element_rect(fill = "white", colour = NA),
        legend.title = element_blank(),
        legend.text = element_text(size = 11),
        axis.text.x = element_text(size = 9),
        strip.text = element_text(size = 10))

ggsave(filename = "figures/goal_scores_panel_plot_highlight.png")
```

